name: clipcap 
channels:
  - conda-forge
dependencies:
- python>=3.8
- pip>=21
- scikit-image=0.18.1
- pip:
   - transformers~=4.10.2
   - ftfy
   - regex
   - tqdm
   - mlflow
   - git+https://github.com/openai/CLIP.git
